### ISSUE TITLE
1.18报错，且默认配置文件乱码paper1.18

### ISSUE THREAD

**Issue by maolaoya** [carm-outsource/TimeReward#1]
**问题简述**
   输入指令报错

**问题来源**
   [15:20:10 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'timereward' in plugin TimeReward v1.3.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2081) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-198]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-198]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
描述一下通过哪些操作才发现的问题，如：
  输入指令中显示"An internal error......."

**Comment by CarmJos** [comment]
您好，插件没有正常加载，故输入指令提示此报错。我这里猜测是没有配置数据库，具体请您看插件加载时的报错。

若您是Windows服务器，请启用UTF-8支持即可解决配置文件乱码的问题。

**Comment by maolaoya** [comment]
编码问题已解决，但是如何在不懂如何使用MQ数据库，转配置为SQ？不然好像插件无法使用

**Comment by CarmJos** [comment]
目前只支持MySQL或MariaDB哦。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月4日(周五) 下午3:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CarmJos/TimeReward] 1.18报错，且默认配置文件乱码paper1.18 (Issue #1)




 
编码问题已解决，但是如何在不懂如何使用MQ数据库，转配置为SQ？不然好像插件无法使用

**Comment by maolaoya** [comment]
好的 感谢回复 希望后续功能能支持SQ，感谢！

**Comment by CarmJos** [comment]
您这个SQ是指SQLite吗？

**Comment by maolaoya** [comment]
是的

**Comment by CarmJos** [comment]
如果是单个服务器的话没有必要使用本插件，有其他更好的同类插件可以使用哦～
