### ISSUE TITLE
[1.19]无法连接数据库

### ISSUE THREAD

**Issue by windy664** [carm-outsource/TimeReward#2]
**问题简述**

无法连接数据库，且已创建数据库

**问题来源**

**预期结果**(可选)

**问题截图/问题报错**

`[08:12:50 INFO] [Console]: [TimeReward]         创建插件所需表...
[08:12:50 INFO] [Console]: [TimeReward] [ERROR] 无法创建插件所需的表，请检查数据库权限。
[08:12:50 ERROR] [STDERR]: java.sql.SQLSyntaxErrorException: Invalid default value for 'update'
[08:12:50 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.29/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[08:12:50 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.29/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[08:12:50 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.29/com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335)
[08:12:50 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.29/com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2085)
[08:12:50 ERROR] [STDERR]:      at MC-BOOTSTRAP/mysql.connector.java@8.0.29/com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246)
[08:12:50 ERROR] [STDERR]:      at cc.carm.plugin.timereward.lib.easysql.beecp.pool.ProxyStatement.executeUpdate(ProxyStatement.java)
[08:12:50 ERROR] [STDERR]:      at cc.carm.plugin.timereward.lib.easysql.action.SQLUpdateActionImpl.execute(SQLUpdateActionImpl.java:29)
[08:12:50 ERROR] [STDERR]:      at cc.carm.plugin.timereward.lib.easysql.action.SQLUpdateActionImpl.execute(SQLUpdateActionImpl.java:12)
[08:12:50 ERROR] [STDERR]:      at cc.carm.plugin.timereward.database.DataManager.initialize(DataManager.java:41)
[08:12:50 ERROR] [STDERR]:      at cc.carm.plugin.timereward.Main.initialize(Main.java:45)
[08:12:50 ERROR] [STDERR]:      at cc.carm.plugin.timereward.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:53)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServerMixin.java:525)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.1-0550c6cd/org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServerMixin.java:439)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zfo000$arclight$enablePlugins(MinecraftServerMixin.java:2194)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:375)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:300)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:165)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2087)
[08:12:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[08:12:50 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[08:12:50 INFO] [Console]: [TimeReward] [ERROR] 初始化数据库失败，请检查配置文件。
[08:12:50 INFO] [Console]: [TimeReward]         关闭数据库连接...`
**操作环境**

1.19.2 Arclight Java18 /verion无效指令啊....
**其他补充**

`# TimeReward - 区域保护插件，将不符合条件的玩家弹出区域，基于EasyPlugin实现。
# 项目地址: https://github.com/CarmJos/TimeReward
# 下载地址: https://github.com/CarmJos/TimeReward/releases
version: 1.3.0

debug: false

# 统计数据设定
# 该选项用于帮助开发者统计插件版本与使用情况，且绝不会影响性能与使用体验。
# 当然，您也可以选择在这里关闭，或在plugins/bStats下的配置文件中关闭。
metrics: true

# 检查更新设定
# 该选项用于插件判断是否要检查更新，若您不希望插件检查更新并提示您，可以选择关闭。
# 检查更新为异步操作，绝不会影响性能与使用体验。
check-update: true

database:
  # 数据库驱动路径，默认为 MySQL
  driver: com.mysql.cj.jdbc.Driver
  # 数据库连接配置
  host: 127.0.0.1
  port: 3306
  database: minecraft
  username: minecraft
  password: 7L5JtcjdnmYbb7GR
  additional: ?useSSL=false
  # 插件相关表的名称
  tables:
    claimed: tr_user_claimed
    time: tr_user_times

# 奖励相关配置
rewards:
  example:
    name: '&f[初级奖励] &e总在线时长 2小时'
    time: 7200
    permission: servername.vip
    commands:
    - 'say &f恭喜 &b%player_name% &f领取了奖励 &r%(name) &f！ '
`

**Comment by CarmJos** [comment]
请问是什么数据库呀，数据库是什么版本呢。
