### ISSUE TITLE
当达到时间的时候提醒玩家领取奖励

### ISSUE THREAD

**Issue by ZherKing** [carm-outsource/TimeReward#8]
**功能简述**

当我设置30分钟的奖励时间时
一旦在线超过30分钟 服务器便提醒玩家领取奖励（在  auto-claim 关掉的前提下）
**需求来源**

以下为我的配置 （当打开auto-claim）
```yaml
  30:
    name: '&f在线时长 &b30 &f分钟'
    time: 1800
    permission: "timereward.claim"
    commands:
    - 'msg %player_name% 你可以领取在线30分钟的时长奖励(命令 /zaixian)'
```
流程：时间到了——》tr提醒玩家领取插件——》玩家根据命令打开zaixian菜单——》菜单通过判断玩家是否实现目标来进行奖励

当   auto-claim 关掉之后 按照config的提示 “若关闭，则玩家需要手动输入指令领取奖励。”
可以得知 当我关掉后 玩家需要额外输出指令才能有以上的提示
所以我觉得可以增加一个功能 就是专门给关掉auto-claim的人用的功能：提醒玩家领取奖励
**功能参考**(可选)

暂时想不到
**附加内容**

上次发issue忘记说明这个东西了 仅说明添加auto-claim功能 忘记这个东西了
我到现在才发现更新了（）虽然还没测试 看了配置文件才发现了这个东西

**Comment by CarmJos** [comment]
请下载 [此处构建](https://github.com/carm-outsource/TimeReward/actions/runs/4628615147) 并帮助我进行测试。

本构建中，移除了全局的`functions.auto-claim`配置，改为针对于每个奖励物品的`auto`配置，该配置决定该奖励是否自动领取，可以不设置，默认为true。若关闭该奖励的自动领取，则需要玩家手动输入/tr claim 领取奖励。

**Comment by ZherKing** [comment]
> 

这是构建失败了吗

**Comment by CarmJos** [comment]
> > 
> 
> 这是构建失败了吗

我已重新提交构建，请再看一眼叭。

**Comment by ZherKing** [comment]
> > > 
> > 
> > 
> > 这是构建失败了吗
> 
> 我已重新提交构建，请再看一眼叭。

来了来了 人在学校没及时回复 我将于下午进行测试 测试完后我将会回复结果！

**Comment by CarmJos** [comment]
> > > > 
> > > 
> > > 
> > > 这是构建失败了吗
> > 
> > 
> > 我已重新提交构建，请再看一眼叭。
> 
> 来了来了 人在学校没及时回复 我将于下午进行测试 测试完后我将会回复结果！

好的，感谢您的回复，静待佳音。

**Comment by ZherKing** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 这是构建失败了吗
> > > 
> > > 
> > > 我已重新提交构建，请再看一眼叭。
> > 
> > 
> > 来了来了 人在学校没及时回复 我将于下午进行测试 测试完后我将会回复结果！
> 
> 好的，感谢您的回复，静待佳音。

那时候发现构建下来的文件过期了
于是自己构建了下
启动的时候出现了错误 不知道是我的构建问题吗
启动错误如下
```
[16:39:15 ERROR]: Could not load 'plugins\timereward-2.2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: cc/carm/lib/easyplugin/EasyPlugin
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:158) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:413) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:321) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:436) ~[paper-1.19.3.jar:git-Paper-378]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-378]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: cc/carm/lib/easyplugin/EasyPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:223) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:495) ~[?:?]
        at java.lang.Class.forName(Class.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:154) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: cc.carm.lib.easyplugin.EasyPlugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:223) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:495) ~[?:?]
        at java.lang.Class.forName(Class.java:474) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:154) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 7 more
```

**Comment by ZherKing** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 这是构建失败了吗
> > > 
> > > 
> > > 我已重新提交构建，请再看一眼叭。
> > 
> > 
> > 来了来了 人在学校没及时回复 我将于下午进行测试 测试完后我将会回复结果！
> 
> 好的，感谢您的回复，静待佳音。

请问能否再次提供一份构建文件方便我进行测试
由于在学校错过了下载文件的机会

**Comment by ZherKing** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 这是构建失败了吗
> > > 
> > > 
> > > 我已重新提交构建，请再看一眼叭。
> > 
> > 
> > 来了来了 人在学校没及时回复 我将于下午进行测试 测试完后我将会回复结果！
> 
> 好的，感谢您的回复，静待佳音。

我今天晚上和明天中午之前都有空可以进行测试 等到明天下午我将要去学校了

**Comment by CarmJos** [comment]
您好，已重新提交编译，请 [点击这里](https://github.com/carm-outsource/TimeReward/actions/runs/4628615147) 下载构件。

**Comment by ZherKing** [comment]
> 您好，已重新提交编译，请 [点击这里](https://github.com/carm-outsource/TimeReward/actions/runs/4628615147) 下载构件。

收到文件 TimeReward-2.2.0.jar 已经进行测试 插件可以正常运行
经过测试发现 "服务器便提醒玩家领取奖励（在 auto-claim 关掉的前提下）" 这一个要求没有出现
需要在配置文件夹中 设置 auto: true 才会出现提醒玩家
以下为我的配置文件
```
rewards:
  example:
    time: 20
    name: '&f[初级奖励] &e总在线时长 2小时'
    permission:
    commands:
    - say &f输入/zaixian领取奖励
    auto: false
  example1:
    time: 21
    name: '&f[初级奖励] &e总在线时长 2小时'
    permission:
    commands:
    - say &f恭喜 &b%player_name% &f领取了奖励 &r%(name) &f！
    auto: true
```
当达到 20 秒的时候应当提醒玩家输入 /zaixian 进行奖励的提取 可是 auto:false 后便没有提示
我又返回去看了下文档 发现了
```
# %TimeReward_claimable_<奖励ID>%
- 得到玩家是否可以领取某个奖励 
```
当我打开auto的时候 这个功能变成没用 因为时间不够无法领取 一到时间自动领取 两个都是输出了 false
总结下来 我认为该插件应该另外添加
另一个配置来提醒玩家领取东西（ auto: false 的情况下）
这是我想到的配置（第一种）：
```
rewards:
  example:
    time: 20
    name: '&f[初级奖励] &e总在线时长 2小时'
    permission:
    messgae: "输入/zaixian领取奖励"
    commands:
    - say &f恭喜 &b%player_name% &f领取了奖励 &r%(name) &f！
    auto: false
```
其中 commands 栏和 message 栏中是分别作为auto开和关的处理结果
我认为： auto: false 的时候 可以用 message 的信息 当打开的时候就是用 commands
（第二种）可以尝试在 config.yml 中添加一个开关
```
message：false
# 服务器消息提醒显示
# 该选项用于当 rewards 中 auto: false 的时候可以使用 message 中的消息提示
# 当 auto: true 打开的时候默认禁用 message
```
在message.yml添加
```
have-rewards:
- '&f你当前有奖励可以领取！'
```
可以让玩家被动的输入  /tr user claim 来领取奖励

我的语言表达能力并不强 有一些文字可能读不懂什么意思 见谅

**Comment by CarmJos** [comment]
您好，请利用`auto: false`实现消息的提示功能。您可以依照该格式配置：

```yaml
rewards:
  example:
    time: 20
    name: '初级奖励提示'
    commands:
    - say &f输入/zaixian领取奖励
    auto: true
  example1:
    time: 20
    name: '&f[初级奖励] &e总在线时长 2小时'
    commands:
    - say &f恭喜 &b%player_name% &f领取了奖励 &r%(name) &f！
    auto: false
```

**Comment by ZherKing** [comment]
> 您好，请利用`auto: false`实现消息的提示功能。您可以依照该格式配置：
> 
> ```yaml
> rewards:
>   example:
>     time: 20
>     name: '初级奖励提示'
>     commands:
>     - say &f输入/zaixian领取奖励
>     auto: true
>   example1:
>     time: 20
>     name: '&f[初级奖励] &e总在线时长 2小时'
>     commands:
>     - say &f恭喜 &b%player_name% &f领取了奖励 &r%(name) &f！
>     auto: false
> ```

！？我还真没想到这个
那我应该是没什么问题了！可以发布新版本了

**Comment by CarmJos** [comment]
好的，感谢您的建议，我将在稍后发版。
